[App]
Name = "ai.h2o.hospital_sim"
Version = "0.1.1"
Title = "Hospital Capacity Simulation"
Description = "Simulate hospital capacity with synthetic patient data and MOJO predictions"
Category = "Healthcare"
Keywords = ["hospital"]
LongDescription = "about.md"

[Runtime]
Module = "src.start"

[[Env]]
Name = "DAI_LICENSE"
Secret = "dai-license"
SecretKey = "license.sig"