[App]
Name = "wave-databricks"
Version = "0.0.5"
Title = "Wave Databricks Notebook Generator"
Description = "Generate a Databricks Notebook based on user settings"
Category = "Data Science"
LongDescription = "about.md"

[Runtime]
Module = "src.app"
MemoryLimit = "200Mi"
MemoryReservation = "100Mi"

