[App]
Name = "mlops-test"
Version = "0.1.0"
Title = "MLOps Demo"
Description = "Steam/DAI and MLOps Demo"
Category = "Other"
LongDescription = "about.md"

[Runtime]
Module = "src.app"
MemoryLimit = "200Mi"
MemoryReservation = "100Mi"
EnableOIDC = true

[[Env]]
Name = "STORAGE_URL"
Secret = "h2oai-mlops"
SecretKey = "gateway"
