[App]
Name = "mlops-test"
Version = "0.0.1"
Title = "mlops test"
Description = "App that demonstrates MLOps integration"
Category = "Other"

[Runtime]
Module = "src.app"
MemoryLimit = "200Mi"
MemoryReservation = "100Mi"
EnableOIDC = true

[[Env]]
Name = "STORAGE_URL"
Secret = "h2oai-mlops"
SecretKey = "gateway"
