[App]
Name = "mlops-test"
Version = "0.2.5"
Title = "Steam & MLOps Demo"
Description = "Demo of Steam, DAI and MLOps in Wave cloud"
Category = "Other"
LongDescription = "about.md"

[Runtime]
Module = "src.app"
MemoryLimit = "200Mi"
MemoryReservation = "100Mi"
EnableOIDC = true

[[Env]]
Name = "STORAGE_URL"
Secret = "h2oai-mlops"
SecretKey = "gateway"

[[Env]]
Name = "STEAM_URL"
Secret = "h2oai-steam"
SecretKey = "api"

